// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqID4p3MA5AGoEkBhEZV5Cnl6xjWmGW3Y',
    appId: '1:628102576289:web:19658a01e81a0c5ddfd8e0',
    messagingSenderId: '628102576289',
    projectId: 'carrental-c3718',
    authDomain: 'carrental-c3718.firebaseapp.com',
    storageBucket: 'carrental-c3718.firebasestorage.app',
    measurementId: 'G-VNB6X2LTXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0rtyV-aXGq3ba4NzEq2wLEyZte5fv2b4',
    appId: '1:628102576289:android:a51ba55cc86fddbfdfd8e0',
    messagingSenderId: '628102576289',
    projectId: 'carrental-c3718',
    storageBucket: 'carrental-c3718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7FtcONUZnMb3Mk3RlsdvqFfN73DK1v4A',
    appId: '1:628102576289:ios:8fa4e3d91e184dd6dfd8e0',
    messagingSenderId: '628102576289',
    projectId: 'carrental-c3718',
    storageBucket: 'carrental-c3718.firebasestorage.app',
    iosBundleId: 'com.ab.carrental',
  );
}
